package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="rent"
)
public class Admin  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String prenom;
     private long cin;
     private String login;
     private String motpass;
     private Set<Agence> agences = new HashSet<Agence>(0);

    public Admin() {
    }

	
    public Admin(String nom, String prenom, long cin, String login, String motpass) {
        this.nom = nom;
        this.prenom = prenom;
        this.cin = cin;
        this.login = login;
        this.motpass = motpass;
    }
    public Admin(String nom, String prenom, long cin, String login, String motpass, Set<Agence> agences) {
       this.nom = nom;
       this.prenom = prenom;
       this.cin = cin;
       this.login = login;
       this.motpass = motpass;
       this.agences = agences;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nom", nullable=false, length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", nullable=false, length=50)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="cin", nullable=false)
    public long getCin() {
        return this.cin;
    }
    
    public void setCin(long cin) {
        this.cin = cin;
    }

    
    @Column(name="login", nullable=false, length=50)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="motpass", nullable=false, length=50)
    public String getMotpass() {
        return this.motpass;
    }
    
    public void setMotpass(String motpass) {
        this.motpass = motpass;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set<Agence> getAgences() {
        return this.agences;
    }
    
    public void setAgences(Set<Agence> agences) {
        this.agences = agences;
    }




}


