package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Agence generated by hbm2java
 */
@Entity
@Table(name="agence"
    ,catalog="rent"
)
public class Agence  implements java.io.Serializable {


     private Integer id;
     private Admin admin;
     private String nomAgence;
     private String adresse;
     private int tel;
     private int fax;
     private int gsm;
     private String fiscale;
     private String email;

    public Agence() {
    }

    public Agence(Admin admin, String nomAgence, String adresse, int tel, int fax, int gsm, String fiscale, String email) {
       this.admin = admin;
       this.nomAgence = nomAgence;
       this.adresse = adresse;
       this.tel = tel;
       this.fax = fax;
       this.gsm = gsm;
       this.fiscale = fiscale;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_admin", nullable=false)
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    
    @Column(name="nom_agence", nullable=false, length=50)
    public String getNomAgence() {
        return this.nomAgence;
    }
    
    public void setNomAgence(String nomAgence) {
        this.nomAgence = nomAgence;
    }

    
    @Column(name="adresse", nullable=false, length=50)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="tel", nullable=false)
    public int getTel() {
        return this.tel;
    }
    
    public void setTel(int tel) {
        this.tel = tel;
    }

    
    @Column(name="fax", nullable=false)
    public int getFax() {
        return this.fax;
    }
    
    public void setFax(int fax) {
        this.fax = fax;
    }

    
    @Column(name="gsm", nullable=false)
    public int getGsm() {
        return this.gsm;
    }
    
    public void setGsm(int gsm) {
        this.gsm = gsm;
    }

    
    @Column(name="fiscale", nullable=false, length=50)
    public String getFiscale() {
        return this.fiscale;
    }
    
    public void setFiscale(String fiscale) {
        this.fiscale = fiscale;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


