package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Assocontratconducteur generated by hbm2java
 */
@Entity
@Table(name="assocontratconducteur"
    ,catalog="rent"
)
public class Assocontratconducteur  implements java.io.Serializable {


     private Integer id;
     private Conducteur conducteur;
     private Contrat contrat;

    public Assocontratconducteur() {
    }

    public Assocontratconducteur(Conducteur conducteur, Contrat contrat) {
       this.conducteur = conducteur;
       this.contrat = contrat;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_conducteur1", nullable=false)
    public Conducteur getConducteur() {
        return this.conducteur;
    }
    
    public void setConducteur(Conducteur conducteur) {
        this.conducteur = conducteur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_contrat", nullable=false)
    public Contrat getContrat() {
        return this.contrat;
    }
    
    public void setContrat(Contrat contrat) {
        this.contrat = contrat;
    }




}


