package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Assocontratpai generated by hbm2java
 */
@Entity
@Table(name="assocontratpai"
    ,catalog="rent"
)
public class Assocontratpai  implements java.io.Serializable {


     private Integer id;
     private Contrat contrat;
     private Paiment paiment;

    public Assocontratpai() {
    }

    public Assocontratpai(Contrat contrat, Paiment paiment) {
       this.contrat = contrat;
       this.paiment = paiment;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_contrat", nullable=false)
    public Contrat getContrat() {
        return this.contrat;
    }
    
    public void setContrat(Contrat contrat) {
        this.contrat = contrat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pai", nullable=false)
    public Paiment getPaiment() {
        return this.paiment;
    }
    
    public void setPaiment(Paiment paiment) {
        this.paiment = paiment;
    }




}


