package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Assocontratclient generated by hbm2java
 */
@Entity
@Table(name="assocontratclient"
    ,catalog="rent"
)
public class Assocontratclient  implements java.io.Serializable {


     private Integer id;
     private Client client;
     private Contrat contrat;

    public Assocontratclient() {
    }

    public Assocontratclient(Client client, Contrat contrat) {
       this.client = client;
       this.contrat = contrat;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_client", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_contrat", nullable=false)
    public Contrat getContrat() {
        return this.contrat;
    }
    
    public void setContrat(Contrat contrat) {
        this.contrat = contrat;
    }




}


