package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Autrrecet generated by hbm2java
 */
@Entity
@Table(name="autrrecet"
    ,catalog="rent"
)
public class Autrrecet  implements java.io.Serializable {


     private Integer id;
     private float montant;
     private String remarque;
     private Date date;
     private int etat;

    public Autrrecet() {
    }

    public Autrrecet(float montant, String remarque, Date date, int etat) {
       this.montant = montant;
       this.remarque = remarque;
       this.date = date;
       this.etat = etat;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="montant", nullable=false, precision=12, scale=0)
    public float getMontant() {
        return this.montant;
    }
    
    public void setMontant(float montant) {
        this.montant = montant;
    }

    
    @Column(name="remarque", nullable=false, length=50)
    public String getRemarque() {
        return this.remarque;
    }
    
    public void setRemarque(String remarque) {
        this.remarque = remarque;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="etat", nullable=false)
    public int getEtat() {
        return this.etat;
    }
    
    public void setEtat(int etat) {
        this.etat = etat;
    }




}


