package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog="rent"
)
public class Client  implements java.io.Serializable {


     private Integer id;
     private String nomprenom;
     private Date dateNaiss;
     private String lieuNaiss;
     private String nationalite;
     private String email;
     private long tel;
     private String adresse;
     private long identite;
     private String type;
     private Date delivre;
     private String lieuDelivr;
     private int etat;
     private Set<Assocontratclient> assocontratclients = new HashSet<Assocontratclient>(0);

    public Client() {
    }

	
    public Client(String nomprenom, Date dateNaiss, String lieuNaiss, String nationalite, String email, long tel, String adresse, long identite, String type, Date delivre, String lieuDelivr, int etat) {
        this.nomprenom = nomprenom;
        this.dateNaiss = dateNaiss;
        this.lieuNaiss = lieuNaiss;
        this.nationalite = nationalite;
        this.email = email;
        this.tel = tel;
        this.adresse = adresse;
        this.identite = identite;
        this.type = type;
        this.delivre = delivre;
        this.lieuDelivr = lieuDelivr;
        this.etat = etat;
    }
    public Client(String nomprenom, Date dateNaiss, String lieuNaiss, String nationalite, String email, long tel, String adresse, long identite, String type, Date delivre, String lieuDelivr, int etat, Set<Assocontratclient> assocontratclients) {
       this.nomprenom = nomprenom;
       this.dateNaiss = dateNaiss;
       this.lieuNaiss = lieuNaiss;
       this.nationalite = nationalite;
       this.email = email;
       this.tel = tel;
       this.adresse = adresse;
       this.identite = identite;
       this.type = type;
       this.delivre = delivre;
       this.lieuDelivr = lieuDelivr;
       this.etat = etat;
       this.assocontratclients = assocontratclients;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nomprenom", nullable=false, length=50)
    public String getNomprenom() {
        return this.nomprenom;
    }
    
    public void setNomprenom(String nomprenom) {
        this.nomprenom = nomprenom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_naiss", nullable=false, length=10)
    public Date getDateNaiss() {
        return this.dateNaiss;
    }
    
    public void setDateNaiss(Date dateNaiss) {
        this.dateNaiss = dateNaiss;
    }

    
    @Column(name="lieu_naiss", nullable=false, length=50)
    public String getLieuNaiss() {
        return this.lieuNaiss;
    }
    
    public void setLieuNaiss(String lieuNaiss) {
        this.lieuNaiss = lieuNaiss;
    }

    
    @Column(name="nationalite", nullable=false, length=50)
    public String getNationalite() {
        return this.nationalite;
    }
    
    public void setNationalite(String nationalite) {
        this.nationalite = nationalite;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="tel", nullable=false)
    public long getTel() {
        return this.tel;
    }
    
    public void setTel(long tel) {
        this.tel = tel;
    }

    
    @Column(name="adresse", nullable=false, length=50)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="identite", nullable=false)
    public long getIdentite() {
        return this.identite;
    }
    
    public void setIdentite(long identite) {
        this.identite = identite;
    }

    
    @Column(name="type", nullable=false, length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="delivre", nullable=false, length=10)
    public Date getDelivre() {
        return this.delivre;
    }
    
    public void setDelivre(Date delivre) {
        this.delivre = delivre;
    }

    
    @Column(name="lieu_delivr", nullable=false, length=50)
    public String getLieuDelivr() {
        return this.lieuDelivr;
    }
    
    public void setLieuDelivr(String lieuDelivr) {
        this.lieuDelivr = lieuDelivr;
    }

    
    @Column(name="etat", nullable=false)
    public int getEtat() {
        return this.etat;
    }
    
    public void setEtat(int etat) {
        this.etat = etat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Assocontratclient> getAssocontratclients() {
        return this.assocontratclients;
    }
    
    public void setAssocontratclients(Set<Assocontratclient> assocontratclients) {
        this.assocontratclients = assocontratclients;
    }




}


