package Model;
// Generated 13 d�c. 2017 11:10:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Coleur generated by hbm2java
 */
@Entity
@Table(name="coleur"
    ,catalog="rent"
)
public class Coleur  implements java.io.Serializable {


     private Integer id;
     private String coleur;

    public Coleur() {
    }

    public Coleur(String coleur) {
       this.coleur = coleur;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="coleur", nullable=false, length=50)
    public String getColeur() {
        return this.coleur;
    }
    
    public void setColeur(String coleur) {
        this.coleur = coleur;
    }

public String toString() {
    return getColeur();
}


}


