package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conducteur generated by hbm2java
 */
@Entity
@Table(name="conducteur"
    ,catalog="rent"
)
public class Conducteur  implements java.io.Serializable {


     private Integer id;
     private String nompre;
     private long npermis;
     private Date dateperm;
     private String permisDelivr;
     private long identite;
     private String type;
     private Date dateIdent;
     private String realisIdenti;
     private int etat;
     private Set<Assocontratconducteur> assocontratconducteurs = new HashSet<Assocontratconducteur>(0);
     private Set<Assocontratconducteur2> assocontratconducteur2s = new HashSet<Assocontratconducteur2>(0);

    public Conducteur() {
    }

	
    public Conducteur(String nompre, long npermis, Date dateperm, String permisDelivr, long identite, String type, Date dateIdent, String realisIdenti, int etat) {
        this.nompre = nompre;
        this.npermis = npermis;
        this.dateperm = dateperm;
        this.permisDelivr = permisDelivr;
        this.identite = identite;
        this.type = type;
        this.dateIdent = dateIdent;
        this.realisIdenti = realisIdenti;
        this.etat = etat;
    }
    public Conducteur(String nompre, long npermis, Date dateperm, String permisDelivr, long identite, String type, Date dateIdent, String realisIdenti, int etat, Set<Assocontratconducteur> assocontratconducteurs, Set<Assocontratconducteur2> assocontratconducteur2s) {
       this.nompre = nompre;
       this.npermis = npermis;
       this.dateperm = dateperm;
       this.permisDelivr = permisDelivr;
       this.identite = identite;
       this.type = type;
       this.dateIdent = dateIdent;
       this.realisIdenti = realisIdenti;
       this.etat = etat;
       this.assocontratconducteurs = assocontratconducteurs;
       this.assocontratconducteur2s = assocontratconducteur2s;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nompre", nullable=false, length=50)
    public String getNompre() {
        return this.nompre;
    }
    
    public void setNompre(String nompre) {
        this.nompre = nompre;
    }

    
    @Column(name="npermis", nullable=false)
    public long getNpermis() {
        return this.npermis;
    }
    
    public void setNpermis(long npermis) {
        this.npermis = npermis;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateperm", nullable=false, length=10)
    public Date getDateperm() {
        return this.dateperm;
    }
    
    public void setDateperm(Date dateperm) {
        this.dateperm = dateperm;
    }

    
    @Column(name="permis_delivr", nullable=false, length=50)
    public String getPermisDelivr() {
        return this.permisDelivr;
    }
    
    public void setPermisDelivr(String permisDelivr) {
        this.permisDelivr = permisDelivr;
    }

    
    @Column(name="identite", nullable=false)
    public long getIdentite() {
        return this.identite;
    }
    
    public void setIdentite(long identite) {
        this.identite = identite;
    }

    
    @Column(name="type", nullable=false, length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_ident", nullable=false, length=10)
    public Date getDateIdent() {
        return this.dateIdent;
    }
    
    public void setDateIdent(Date dateIdent) {
        this.dateIdent = dateIdent;
    }

    
    @Column(name="realis_identi", nullable=false, length=50)
    public String getRealisIdenti() {
        return this.realisIdenti;
    }
    
    public void setRealisIdenti(String realisIdenti) {
        this.realisIdenti = realisIdenti;
    }

    
    @Column(name="etat", nullable=false)
    public int getEtat() {
        return this.etat;
    }
    
    public void setEtat(int etat) {
        this.etat = etat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conducteur")
    public Set<Assocontratconducteur> getAssocontratconducteurs() {
        return this.assocontratconducteurs;
    }
    
    public void setAssocontratconducteurs(Set<Assocontratconducteur> assocontratconducteurs) {
        this.assocontratconducteurs = assocontratconducteurs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conducteur")
    public Set<Assocontratconducteur2> getAssocontratconducteur2s() {
        return this.assocontratconducteur2s;
    }
    
    public void setAssocontratconducteur2s(Set<Assocontratconducteur2> assocontratconducteur2s) {
        this.assocontratconducteur2s = assocontratconducteur2s;
    }




}


