package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrat generated by hbm2java
 */
@Entity
@Table(name="contrat"
    ,catalog="rent"
)
public class Contrat  implements java.io.Serializable {


     private Integer id;
     private Date dateContrat;
     private Date dateDep;
     private Date heureDep;
     private Date dateRet;
     private Date heureRet;
     private String lieuDep;
     private String lieuRetour;
     private int kmDep;
     private int kmRetour;
     private int etat;
     private Set<Assocontratpai> assocontratpais = new HashSet<Assocontratpai>(0);
     private Set<Assocontratvoiture> assocontratvoitures = new HashSet<Assocontratvoiture>(0);
     private Set<Facture> factures = new HashSet<Facture>(0);
     private Set<Assocontratconducteur2> assocontratconducteur2s = new HashSet<Assocontratconducteur2>(0);
     private Set<Assocontratclient> assocontratclients = new HashSet<Assocontratclient>(0);
     private Set<Assocontratfact> assocontratfacts = new HashSet<Assocontratfact>(0);
     private Set<Assocontratconducteur> assocontratconducteurs = new HashSet<Assocontratconducteur>(0);
     private Set<Assocontratsocie> assocontratsocies = new HashSet<Assocontratsocie>(0);

    public Contrat() {
    }

	
    public Contrat(Date dateContrat, Date dateDep, Date heureDep, Date dateRet, Date heureRet, String lieuDep, String lieuRetour, int kmDep, int kmRetour, int etat) {
        this.dateContrat = dateContrat;
        this.dateDep = dateDep;
        this.heureDep = heureDep;
        this.dateRet = dateRet;
        this.heureRet = heureRet;
        this.lieuDep = lieuDep;
        this.lieuRetour = lieuRetour;
        this.kmDep = kmDep;
        this.kmRetour = kmRetour;
        this.etat = etat;
    }
    public Contrat(Date dateContrat, Date dateDep, Date heureDep, Date dateRet, Date heureRet, String lieuDep, String lieuRetour, int kmDep, int kmRetour, int etat, Set<Assocontratpai> assocontratpais, Set<Assocontratvoiture> assocontratvoitures, Set<Facture> factures, Set<Assocontratconducteur2> assocontratconducteur2s, Set<Assocontratclient> assocontratclients, Set<Assocontratfact> assocontratfacts, Set<Assocontratconducteur> assocontratconducteurs, Set<Assocontratsocie> assocontratsocies) {
       this.dateContrat = dateContrat;
       this.dateDep = dateDep;
       this.heureDep = heureDep;
       this.dateRet = dateRet;
       this.heureRet = heureRet;
       this.lieuDep = lieuDep;
       this.lieuRetour = lieuRetour;
       this.kmDep = kmDep;
       this.kmRetour = kmRetour;
       this.etat = etat;
       this.assocontratpais = assocontratpais;
       this.assocontratvoitures = assocontratvoitures;
       this.factures = factures;
       this.assocontratconducteur2s = assocontratconducteur2s;
       this.assocontratclients = assocontratclients;
       this.assocontratfacts = assocontratfacts;
       this.assocontratconducteurs = assocontratconducteurs;
       this.assocontratsocies = assocontratsocies;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_contrat", nullable=false, length=10)
    public Date getDateContrat() {
        return this.dateContrat;
    }
    
    public void setDateContrat(Date dateContrat) {
        this.dateContrat = dateContrat;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_dep", nullable=false, length=10)
    public Date getDateDep() {
        return this.dateDep;
    }
    
    public void setDateDep(Date dateDep) {
        this.dateDep = dateDep;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="heure_dep", nullable=false, length=8)
    public Date getHeureDep() {
        return this.heureDep;
    }
    
    public void setHeureDep(Date heureDep) {
        this.heureDep = heureDep;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_ret", nullable=false, length=10)
    public Date getDateRet() {
        return this.dateRet;
    }
    
    public void setDateRet(Date dateRet) {
        this.dateRet = dateRet;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="heure_ret", nullable=false, length=8)
    public Date getHeureRet() {
        return this.heureRet;
    }
    
    public void setHeureRet(Date heureRet) {
        this.heureRet = heureRet;
    }

    
    @Column(name="lieu_dep", nullable=false, length=50)
    public String getLieuDep() {
        return this.lieuDep;
    }
    
    public void setLieuDep(String lieuDep) {
        this.lieuDep = lieuDep;
    }

    
    @Column(name="lieu_retour", nullable=false, length=50)
    public String getLieuRetour() {
        return this.lieuRetour;
    }
    
    public void setLieuRetour(String lieuRetour) {
        this.lieuRetour = lieuRetour;
    }

    
    @Column(name="km_dep", nullable=false)
    public int getKmDep() {
        return this.kmDep;
    }
    
    public void setKmDep(int kmDep) {
        this.kmDep = kmDep;
    }

    
    @Column(name="km_retour", nullable=false)
    public int getKmRetour() {
        return this.kmRetour;
    }
    
    public void setKmRetour(int kmRetour) {
        this.kmRetour = kmRetour;
    }

    
    @Column(name="etat", nullable=false)
    public int getEtat() {
        return this.etat;
    }
    
    public void setEtat(int etat) {
        this.etat = etat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrat")
    public Set<Assocontratpai> getAssocontratpais() {
        return this.assocontratpais;
    }
    
    public void setAssocontratpais(Set<Assocontratpai> assocontratpais) {
        this.assocontratpais = assocontratpais;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrat")
    public Set<Assocontratvoiture> getAssocontratvoitures() {
        return this.assocontratvoitures;
    }
    
    public void setAssocontratvoitures(Set<Assocontratvoiture> assocontratvoitures) {
        this.assocontratvoitures = assocontratvoitures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrat")
    public Set<Facture> getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set<Facture> factures) {
        this.factures = factures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrat")
    public Set<Assocontratconducteur2> getAssocontratconducteur2s() {
        return this.assocontratconducteur2s;
    }
    
    public void setAssocontratconducteur2s(Set<Assocontratconducteur2> assocontratconducteur2s) {
        this.assocontratconducteur2s = assocontratconducteur2s;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrat")
    public Set<Assocontratclient> getAssocontratclients() {
        return this.assocontratclients;
    }
    
    public void setAssocontratclients(Set<Assocontratclient> assocontratclients) {
        this.assocontratclients = assocontratclients;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrat")
    public Set<Assocontratfact> getAssocontratfacts() {
        return this.assocontratfacts;
    }
    
    public void setAssocontratfacts(Set<Assocontratfact> assocontratfacts) {
        this.assocontratfacts = assocontratfacts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrat")
    public Set<Assocontratconducteur> getAssocontratconducteurs() {
        return this.assocontratconducteurs;
    }
    
    public void setAssocontratconducteurs(Set<Assocontratconducteur> assocontratconducteurs) {
        this.assocontratconducteurs = assocontratconducteurs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrat")
    public Set<Assocontratsocie> getAssocontratsocies() {
        return this.assocontratsocies;
    }
    
    public void setAssocontratsocies(Set<Assocontratsocie> assocontratsocies) {
        this.assocontratsocies = assocontratsocies;
    }




}


