package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Depensevoit generated by hbm2java
 */
@Entity
@Table(name="depensevoit"
    ,catalog="rent"
)
public class Depensevoit  implements java.io.Serializable {


     private Integer id;
     private Voiture voiture;
     private float montant;
     private String remarque;
     private Date date;

    public Depensevoit() {
    }

    public Depensevoit(Voiture voiture, float montant, String remarque, Date date) {
       this.voiture = voiture;
       this.montant = montant;
       this.remarque = remarque;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_veh", nullable=false)
    public Voiture getVoiture() {
        return this.voiture;
    }
    
    public void setVoiture(Voiture voiture) {
        this.voiture = voiture;
    }

    
    @Column(name="montant", nullable=false, precision=12, scale=0)
    public float getMontant() {
        return this.montant;
    }
    
    public void setMontant(float montant) {
        this.montant = montant;
    }

    
    @Column(name="remarque", nullable=false, length=50)
    public String getRemarque() {
        return this.remarque;
    }
    
    public void setRemarque(String remarque) {
        this.remarque = remarque;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


