package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name="facture"
    ,catalog="rent"
)
public class Facture  implements java.io.Serializable {


     private Integer id;
     private Contrat contrat;
     private int numFact;
     private String design;
     private int quantit;
     private Date dateCre;
     private float debit;
     private int etat;
     private Set<Tva> tvas = new HashSet<Tva>(0);
     private Set<Assocontratfact> assocontratfacts = new HashSet<Assocontratfact>(0);

    public Facture() {
    }

	
    public Facture(Contrat contrat, int numFact, String design, int quantit, Date dateCre, float debit, int etat) {
        this.contrat = contrat;
        this.numFact = numFact;
        this.design = design;
        this.quantit = quantit;
        this.dateCre = dateCre;
        this.debit = debit;
        this.etat = etat;
    }
    public Facture(Contrat contrat, int numFact, String design, int quantit, Date dateCre, float debit, int etat, Set<Tva> tvas, Set<Assocontratfact> assocontratfacts) {
       this.contrat = contrat;
       this.numFact = numFact;
       this.design = design;
       this.quantit = quantit;
       this.dateCre = dateCre;
       this.debit = debit;
       this.etat = etat;
       this.tvas = tvas;
       this.assocontratfacts = assocontratfacts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_contrat", nullable=false)
    public Contrat getContrat() {
        return this.contrat;
    }
    
    public void setContrat(Contrat contrat) {
        this.contrat = contrat;
    }

    
    @Column(name="num_fact", nullable=false)
    public int getNumFact() {
        return this.numFact;
    }
    
    public void setNumFact(int numFact) {
        this.numFact = numFact;
    }

    
    @Column(name="design", nullable=false, length=50)
    public String getDesign() {
        return this.design;
    }
    
    public void setDesign(String design) {
        this.design = design;
    }

    
    @Column(name="quantit", nullable=false)
    public int getQuantit() {
        return this.quantit;
    }
    
    public void setQuantit(int quantit) {
        this.quantit = quantit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_cre", nullable=false, length=10)
    public Date getDateCre() {
        return this.dateCre;
    }
    
    public void setDateCre(Date dateCre) {
        this.dateCre = dateCre;
    }

    
    @Column(name="debit", nullable=false, precision=12, scale=0)
    public float getDebit() {
        return this.debit;
    }
    
    public void setDebit(float debit) {
        this.debit = debit;
    }

    
    @Column(name="etat", nullable=false)
    public int getEtat() {
        return this.etat;
    }
    
    public void setEtat(int etat) {
        this.etat = etat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="facture")
    public Set<Tva> getTvas() {
        return this.tvas;
    }
    
    public void setTvas(Set<Tva> tvas) {
        this.tvas = tvas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="facture")
    public Set<Assocontratfact> getAssocontratfacts() {
        return this.assocontratfacts;
    }
    
    public void setAssocontratfacts(Set<Assocontratfact> assocontratfacts) {
        this.assocontratfacts = assocontratfacts;
    }




}


