package Model;
// Generated 13 d�c. 2017 11:10:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Model generated by hbm2java
 */
@Entity
@Table(name="model"
    ,catalog="rent"
)
public class Model  implements java.io.Serializable {


     private Integer id;
     private String model;

    public Model() {
    }

    public Model(String model) {
       this.model = model;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="model", nullable=false, length=50)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
public String toString() {
    return getModel();
}



}


