package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paiment generated by hbm2java
 */
@Entity
@Table(name="paiment"
    ,catalog="rent"
)
public class Paiment  implements java.io.Serializable {


     private Integer id;
     private float gatanti;
     private String typeGatan;
     private float pay;
     private String typePay;
     private Date datePay;
     private String remarque;
     private int etat;
     private Set<Etapepay> etapepays = new HashSet<Etapepay>(0);
     private Set<Assocontratpai> assocontratpais = new HashSet<Assocontratpai>(0);

    public Paiment() {
    }

	
    public Paiment(float gatanti, String typeGatan, float pay, String typePay, Date datePay, String remarque, int etat) {
        this.gatanti = gatanti;
        this.typeGatan = typeGatan;
        this.pay = pay;
        this.typePay = typePay;
        this.datePay = datePay;
        this.remarque = remarque;
        this.etat = etat;
    }
    public Paiment(float gatanti, String typeGatan, float pay, String typePay, Date datePay, String remarque, int etat, Set<Etapepay> etapepays, Set<Assocontratpai> assocontratpais) {
       this.gatanti = gatanti;
       this.typeGatan = typeGatan;
       this.pay = pay;
       this.typePay = typePay;
       this.datePay = datePay;
       this.remarque = remarque;
       this.etat = etat;
       this.etapepays = etapepays;
       this.assocontratpais = assocontratpais;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="gatanti", nullable=false, precision=12, scale=0)
    public float getGatanti() {
        return this.gatanti;
    }
    
    public void setGatanti(float gatanti) {
        this.gatanti = gatanti;
    }

    
    @Column(name="type_gatan", nullable=false, length=50)
    public String getTypeGatan() {
        return this.typeGatan;
    }
    
    public void setTypeGatan(String typeGatan) {
        this.typeGatan = typeGatan;
    }

    
    @Column(name="pay", nullable=false, precision=12, scale=0)
    public float getPay() {
        return this.pay;
    }
    
    public void setPay(float pay) {
        this.pay = pay;
    }

    
    @Column(name="type_pay", nullable=false, length=50)
    public String getTypePay() {
        return this.typePay;
    }
    
    public void setTypePay(String typePay) {
        this.typePay = typePay;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_pay", nullable=false, length=10)
    public Date getDatePay() {
        return this.datePay;
    }
    
    public void setDatePay(Date datePay) {
        this.datePay = datePay;
    }

    
    @Column(name="remarque", nullable=false, length=50)
    public String getRemarque() {
        return this.remarque;
    }
    
    public void setRemarque(String remarque) {
        this.remarque = remarque;
    }

    
    @Column(name="etat", nullable=false)
    public int getEtat() {
        return this.etat;
    }
    
    public void setEtat(int etat) {
        this.etat = etat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paiment")
    public Set<Etapepay> getEtapepays() {
        return this.etapepays;
    }
    
    public void setEtapepays(Set<Etapepay> etapepays) {
        this.etapepays = etapepays;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paiment")
    public Set<Assocontratpai> getAssocontratpais() {
        return this.assocontratpais;
    }
    
    public void setAssocontratpais(Set<Assocontratpai> assocontratpais) {
        this.assocontratpais = assocontratpais;
    }




}


