package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name="reservation"
    ,catalog="rent"
)
public class Reservation  implements java.io.Serializable {


     private Integer id;
     private Voiture voiture;
     private String nompr;
     private long tel;
     private String email;
     private String adress;
     private String remarque;
     private Date dateDepart;
     private Date heureDepart;
     private Date dateRetour;
     private Date heureRetour;
     private Date dateReser;
     private int etat;

    public Reservation() {
    }

    public Reservation(Voiture voiture, String nompr, long tel, String email, String adress, String remarque, Date dateDepart, Date heureDepart, Date dateRetour, Date heureRetour, Date dateReser, int etat) {
       this.voiture = voiture;
       this.nompr = nompr;
       this.tel = tel;
       this.email = email;
       this.adress = adress;
       this.remarque = remarque;
       this.dateDepart = dateDepart;
       this.heureDepart = heureDepart;
       this.dateRetour = dateRetour;
       this.heureRetour = heureRetour;
       this.dateReser = dateReser;
       this.etat = etat;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_veh", nullable=false)
    public Voiture getVoiture() {
        return this.voiture;
    }
    
    public void setVoiture(Voiture voiture) {
        this.voiture = voiture;
    }

    
    @Column(name="nompr", nullable=false, length=50)
    public String getNompr() {
        return this.nompr;
    }
    
    public void setNompr(String nompr) {
        this.nompr = nompr;
    }

    
    @Column(name="tel", nullable=false)
    public long getTel() {
        return this.tel;
    }
    
    public void setTel(long tel) {
        this.tel = tel;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="adress", nullable=false, length=50)
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }

    
    @Column(name="remarque", nullable=false, length=50)
    public String getRemarque() {
        return this.remarque;
    }
    
    public void setRemarque(String remarque) {
        this.remarque = remarque;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_depart", nullable=false, length=10)
    public Date getDateDepart() {
        return this.dateDepart;
    }
    
    public void setDateDepart(Date dateDepart) {
        this.dateDepart = dateDepart;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="heure_depart", nullable=false, length=8)
    public Date getHeureDepart() {
        return this.heureDepart;
    }
    
    public void setHeureDepart(Date heureDepart) {
        this.heureDepart = heureDepart;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_retour", nullable=false, length=10)
    public Date getDateRetour() {
        return this.dateRetour;
    }
    
    public void setDateRetour(Date dateRetour) {
        this.dateRetour = dateRetour;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="heure_retour", nullable=false, length=8)
    public Date getHeureRetour() {
        return this.heureRetour;
    }
    
    public void setHeureRetour(Date heureRetour) {
        this.heureRetour = heureRetour;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_reser", nullable=false, length=10)
    public Date getDateReser() {
        return this.dateReser;
    }
    
    public void setDateReser(Date dateReser) {
        this.dateReser = dateReser;
    }

    
    @Column(name="etat", nullable=false)
    public int getEtat() {
        return this.etat;
    }
    
    public void setEtat(int etat) {
        this.etat = etat;
    }




}


