package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Societe generated by hbm2java
 */
@Entity
@Table(name="societe"
    ,catalog="rent"
)
public class Societe  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String email;
     private String matFiscal;
     private long tel;
     private String adresse;
     private int etat;
     private Set<Assocontratsocie> assocontratsocies = new HashSet<Assocontratsocie>(0);

    public Societe() {
    }

	
    public Societe(String nom, String email, String matFiscal, long tel, String adresse, int etat) {
        this.nom = nom;
        this.email = email;
        this.matFiscal = matFiscal;
        this.tel = tel;
        this.adresse = adresse;
        this.etat = etat;
    }
    public Societe(String nom, String email, String matFiscal, long tel, String adresse, int etat, Set<Assocontratsocie> assocontratsocies) {
       this.nom = nom;
       this.email = email;
       this.matFiscal = matFiscal;
       this.tel = tel;
       this.adresse = adresse;
       this.etat = etat;
       this.assocontratsocies = assocontratsocies;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nom", nullable=false, length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="mat_fiscal", nullable=false, length=50)
    public String getMatFiscal() {
        return this.matFiscal;
    }
    
    public void setMatFiscal(String matFiscal) {
        this.matFiscal = matFiscal;
    }

    
    @Column(name="tel", nullable=false)
    public long getTel() {
        return this.tel;
    }
    
    public void setTel(long tel) {
        this.tel = tel;
    }

    
    @Column(name="adresse", nullable=false, length=50)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="etat", nullable=false)
    public int getEtat() {
        return this.etat;
    }
    
    public void setEtat(int etat) {
        this.etat = etat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="societe")
    public Set<Assocontratsocie> getAssocontratsocies() {
        return this.assocontratsocies;
    }
    
    public void setAssocontratsocies(Set<Assocontratsocie> assocontratsocies) {
        this.assocontratsocies = assocontratsocies;
    }




}


