package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tva generated by hbm2java
 */
@Entity
@Table(name="tva"
    ,catalog="rent"
)
public class Tva  implements java.io.Serializable {


     private Integer id;
     private Facture facture;
     private int tva;
     private int timbre;
     private float thtva;
     private float puhtva;

    public Tva() {
    }

    public Tva(Facture facture, int tva, int timbre, float thtva, float puhtva) {
       this.facture = facture;
       this.tva = tva;
       this.timbre = timbre;
       this.thtva = thtva;
       this.puhtva = puhtva;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fact", nullable=false)
    public Facture getFacture() {
        return this.facture;
    }
    
    public void setFacture(Facture facture) {
        this.facture = facture;
    }

    
    @Column(name="tva", nullable=false)
    public int getTva() {
        return this.tva;
    }
    
    public void setTva(int tva) {
        this.tva = tva;
    }

    
    @Column(name="timbre", nullable=false)
    public int getTimbre() {
        return this.timbre;
    }
    
    public void setTimbre(int timbre) {
        this.timbre = timbre;
    }

    
    @Column(name="thtva", nullable=false, precision=12, scale=0)
    public float getThtva() {
        return this.thtva;
    }
    
    public void setThtva(float thtva) {
        this.thtva = thtva;
    }

    
    @Column(name="puhtva", nullable=false, precision=12, scale=0)
    public float getPuhtva() {
        return this.puhtva;
    }
    
    public void setPuhtva(float puhtva) {
        this.puhtva = puhtva;
    }




}


