package Model;
// Generated 13 déc. 2017 11:10:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Voiture generated by hbm2java
 */
@Entity
@Table(name="voiture"
    ,catalog="rent"
)
public class Voiture  implements java.io.Serializable {


     private Integer id;
     private String immat;
     private String carteGris;
     private int nbrPlace;
     private String cat;
     private String climatise;
     private Date misCircu;
     private String modele;
     private String chassis;
     private int puissance;
     private String couleur;
     private int km;
     private int etatVeh;
     private Set<Autre> autres = new HashSet<Autre>(0);
     private Set<Filtreair> filtreairs = new HashSet<Filtreair>(0);
     private Set<Filtrehuile> filtrehuiles = new HashSet<Filtrehuile>(0);
     private Set<Assocontratvoiture> assocontratvoitures = new HashSet<Assocontratvoiture>(0);
     private Set<Vidange> vidanges = new HashSet<Vidange>(0);
     private Set<Assurance> assurances = new HashSet<Assurance>(0);
     private Set<Visite> visites = new HashSet<Visite>(0);
     private Set<Reservation> reservations = new HashSet<Reservation>(0);
     private Set<Depensevoit> depensevoits = new HashSet<Depensevoit>(0);

    public Voiture() {
    }

	
    public Voiture(String immat, String carteGris, int nbrPlace, String cat, String climatise, Date misCircu, String modele, String chassis, int puissance, String couleur, int km, int etatVeh) {
        this.immat = immat;
        this.carteGris = carteGris;
        this.nbrPlace = nbrPlace;
        this.cat = cat;
        this.climatise = climatise;
        this.misCircu = misCircu;
        this.modele = modele;
        this.chassis = chassis;
        this.puissance = puissance;
        this.couleur = couleur;
        this.km = km;
        this.etatVeh = etatVeh;
    }
    public Voiture(String immat, String carteGris, int nbrPlace, String cat, String climatise, Date misCircu, String modele, String chassis, int puissance, String couleur, int km, int etatVeh, Set<Autre> autres, Set<Filtreair> filtreairs, Set<Filtrehuile> filtrehuiles, Set<Assocontratvoiture> assocontratvoitures, Set<Vidange> vidanges, Set<Assurance> assurances, Set<Visite> visites, Set<Reservation> reservations, Set<Depensevoit> depensevoits) {
       this.immat = immat;
       this.carteGris = carteGris;
       this.nbrPlace = nbrPlace;
       this.cat = cat;
       this.climatise = climatise;
       this.misCircu = misCircu;
       this.modele = modele;
       this.chassis = chassis;
       this.puissance = puissance;
       this.couleur = couleur;
       this.km = km;
       this.etatVeh = etatVeh;
       this.autres = autres;
       this.filtreairs = filtreairs;
       this.filtrehuiles = filtrehuiles;
       this.assocontratvoitures = assocontratvoitures;
       this.vidanges = vidanges;
       this.assurances = assurances;
       this.visites = visites;
       this.reservations = reservations;
       this.depensevoits = depensevoits;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="immat", nullable=false, length=50)
    public String getImmat() {
        return this.immat;
    }
    
    public void setImmat(String immat) {
        this.immat = immat;
    }

    
    @Column(name="carte_gris", nullable=false, length=50)
    public String getCarteGris() {
        return this.carteGris;
    }
    
    public void setCarteGris(String carteGris) {
        this.carteGris = carteGris;
    }

    
    @Column(name="nbr_place", nullable=false)
    public int getNbrPlace() {
        return this.nbrPlace;
    }
    
    public void setNbrPlace(int nbrPlace) {
        this.nbrPlace = nbrPlace;
    }

    
    @Column(name="cat", nullable=false, length=50)
    public String getCat() {
        return this.cat;
    }
    
    public void setCat(String cat) {
        this.cat = cat;
    }

    
    @Column(name="climatise", nullable=false, length=50)
    public String getClimatise() {
        return this.climatise;
    }
    
    public void setClimatise(String climatise) {
        this.climatise = climatise;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mis_circu", nullable=false, length=10)
    public Date getMisCircu() {
        return this.misCircu;
    }
    
    public void setMisCircu(Date misCircu) {
        this.misCircu = misCircu;
    }

    
    @Column(name="modele", nullable=false, length=50)
    public String getModele() {
        return this.modele;
    }
    
    public void setModele(String modele) {
        this.modele = modele;
    }

    
    @Column(name="chassis", nullable=false, length=50)
    public String getChassis() {
        return this.chassis;
    }
    
    public void setChassis(String chassis) {
        this.chassis = chassis;
    }

    
    @Column(name="puissance", nullable=false)
    public int getPuissance() {
        return this.puissance;
    }
    
    public void setPuissance(int puissance) {
        this.puissance = puissance;
    }

    
    @Column(name="couleur", nullable=false, length=50)
    public String getCouleur() {
        return this.couleur;
    }
    
    public void setCouleur(String couleur) {
        this.couleur = couleur;
    }

    
    @Column(name="km", nullable=false)
    public int getKm() {
        return this.km;
    }
    
    public void setKm(int km) {
        this.km = km;
    }

    
    @Column(name="etat_veh", nullable=false)
    public int getEtatVeh() {
        return this.etatVeh;
    }
    
    public void setEtatVeh(int etatVeh) {
        this.etatVeh = etatVeh;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="voiture")
    public Set<Autre> getAutres() {
        return this.autres;
    }
    
    public void setAutres(Set<Autre> autres) {
        this.autres = autres;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="voiture")
    public Set<Filtreair> getFiltreairs() {
        return this.filtreairs;
    }
    
    public void setFiltreairs(Set<Filtreair> filtreairs) {
        this.filtreairs = filtreairs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="voiture")
    public Set<Filtrehuile> getFiltrehuiles() {
        return this.filtrehuiles;
    }
    
    public void setFiltrehuiles(Set<Filtrehuile> filtrehuiles) {
        this.filtrehuiles = filtrehuiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="voiture")
    public Set<Assocontratvoiture> getAssocontratvoitures() {
        return this.assocontratvoitures;
    }
    
    public void setAssocontratvoitures(Set<Assocontratvoiture> assocontratvoitures) {
        this.assocontratvoitures = assocontratvoitures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="voiture")
    public Set<Vidange> getVidanges() {
        return this.vidanges;
    }
    
    public void setVidanges(Set<Vidange> vidanges) {
        this.vidanges = vidanges;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="voiture")
    public Set<Assurance> getAssurances() {
        return this.assurances;
    }
    
    public void setAssurances(Set<Assurance> assurances) {
        this.assurances = assurances;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="voiture")
    public Set<Visite> getVisites() {
        return this.visites;
    }
    
    public void setVisites(Set<Visite> visites) {
        this.visites = visites;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="voiture")
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="voiture")
    public Set<Depensevoit> getDepensevoits() {
        return this.depensevoits;
    }
    
    public void setDepensevoits(Set<Depensevoit> depensevoits) {
        this.depensevoits = depensevoits;
    }




}


